Update app-entrypoint.sh
bitnami/bitnami-docker-laravel pull request #151
Opened 2021-11-15 09:58 UTC by teriiehina

**Description of the change**

Some database references were hard-coded in the `app-entrypoint.sh` file.
They have been replaced by the corresponding variable.

Also, the port number has been added to the log output to help any missing configuration when using another DB engine than MariaDB.

**Benefits**

This change will prevent users (like me) to believe that they containerized laravel app is using MariaDB although the environment variables are set so that the DB engine to use is Postgresql.

**Possible drawbacks**

No drawbacks AFAIK.

**Applicable issues**

No issues AFAIK.

**Additional information**

I lost 30 minutes asking myself «why aren’t the varenvs use by the container 🤔» ... and then «why isn’t the right port number used 🤨» ... I may not be the sharpest tool in the shed 🤣 ...
(you asked for additional informations, not useful ones 😉)

2021-11-16 09:14 UTC, miguelaeh requested changes
Thank you for the PR!
Please take a look at the comments

2021-11-16 09:14 UTC, miguelaeh commented on 8/debian-10/rootfs/app-entrypoint.sh
> +    log "Connecting to $db_host at $db_address:$db_port"
```suggestion
    log "Connecting to database at ${db_address}:${db_port}"
```

2021-11-16 09:14 UTC, miguelaeh commented on 8/debian-10/rootfs/app-entrypoint.sh
> +            log "Error: Couldn't connect to db_host."
```suggestion
            log "Error: Couldn't connect to the database"
```

2021-11-16 20:08 UTC, teriiehina commented on 8/debian-10/rootfs/app-entrypoint.sh
> +    log "Connecting to $db_host at $db_address:$db_port"
I would prefer to use `${db_host}` instead of the `database` as it allows for more information without any drawbacks AFAIK.

2021-11-16 20:08 UTC, teriiehina commented on 8/debian-10/rootfs/app-entrypoint.sh
> +            log "Error: Couldn't connect to db_host."
Same as previous comment, `${db_host}` looks better to me than `database`

2021-11-17 09:32 UTC, miguelaeh commented on 8/debian-10/rootfs/app-entrypoint.sh
> +    log "Connecting to $db_host at $db_address:$db_port"
Hi @teriiehina ,
Could you share which would be the `db_host` string? I see in the lines above that we use that variable to extract the address, so adding both will add redundant information

2021-11-18 20:58 UTC, teriiehina commented on 8/debian-10/rootfs/app-entrypoint.sh
> +    log "Connecting to $db_host at $db_address:$db_port"
hi @miguelaeh ,

indeed, `db_address` would ultimately resolve to `db_host`. my bad 😅 

good for me then :)

2021-11-22 16:53 UTC, miguelaeh approved these changes
LGTM!
I need to perform some changes before merging the PR to release this in all the versions.

2021-11-23 10:28 UTC, merged